source 'https://rubygems.org'

gem 'activesupport', '7.0.7.1'
gem 'elasticsearch-xpack', '7.13.3'
gem 'elasticsearch', '<=7.13.3'
gem 'elasticsearch-api', '<=7.13.3'
gem 'elasticsearch-transport', '<=7.13.3'
gem 'fluentd'
gem 'oj'
gem 'tiny_tds'
gem 'fluent-plugin-concat'
gem 'fluent-plugin-detect-exceptions'
gem 'fluent-plugin-kubernetes_metadata_filter'
gem 'fluent-plugin-multi-format-parser'
gem 'fluent-plugin-systemd'
gem 'fluent-plugin-filter-urldecode'
gem 'fluent-plugin-rename-key'
gem 'fluent-plugin-mssql-lookup'
gem 'fluent-plugin-ua-parser'
gem 'fluent-plugin-aws-elasticsearch-service'
gem 'fluent-plugin-azurestorage-gen2'
gem 'fluent-plugin-cloudwatch-logs'
gem 'fluent-plugin-concat'
gem 'fluent-plugin-datadog'
gem 'fluent-plugin-elasticsearch'
gem 'fluent-plugin-grafana-loki'
gem 'fluent-plugin-forest'
gem 'fluent-plugin-kafka'
gem 'fluent-plugin-opensearch'
gem 'fluent-plugin-prometheus'
gem 'fluent-plugin-record-modifier'
gem 'fluent-plugin-rewrite-tag-filter'
gem 'fluent-plugin-route'
gem 'fluent-plugin-s3'
gem 'fluent-plugin-sqs'
gem 'fluent-plugin-flowcounter'
gem 'fluent-plugin-anonymizer'
gem 'fluent-plugin-mongo'
gem 'fluent-plugin-kubernetes'
gem 'fluent-plugin-timescaledb'
gem 'fluent-plugin-mysql'
gem 'fluent-plugin-postgres'
gem 'fluent-plugin-sql'

